author: Ryo Aoyama
author_url: https://github.com/ra1028
github_url: https://github.com/ra1028/DifferenceKit
module: DifferenceKit
readme: README.md
exclude: Sources/Extensions/AppKitExtension.swift
output: docs
theme: apple
clean: true
skip_undocumented: true
xcodebuild_arguments:
  - -sdk
  - iphonesimulator
  - -scheme
  - DifferenceKit
