#if !canImport(ObjectiveC)
import XCTest

extension AlgorithmTestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AlgorithmTestCase = [
        ("testComplicated1", testComplicated1),
        ("testComplicated10", testComplicated10),
        ("testComplicated11", testComplicated11),
        ("testComplicated2", testComplicated2),
        ("testComplicated3", testComplicated3),
        ("testComplicated4", testComplicated4),
        ("testComplicated5", testComplicated5),
        ("testComplicated6", testComplicated6),
        ("testComplicated7", testComplicated7),
        ("testComplicated8", testComplicated8),
        ("testComplicated9", testComplicated9),
        ("testDeleted", testDeleted),
        ("testDuplicated", testDuplicated),
        ("testDuplicatedElement", testDuplicatedElement),
        ("testDuplicatedSection", testDuplicatedSection),
        ("testDuplicatedSectionAndElement", testDuplicatedSectionAndElement),
        ("testEmptyChangesets", testEmptyChangesets),
        ("testInserted", testInserted),
        ("testMixedChanges", testMixedChanges),
        ("testMixedSectionChanges", testMixedSectionChanges),
        ("testMoved", testMoved),
        ("testSameHashValue", testSameHashValue),
        ("testSectionDeleted", testSectionDeleted),
        ("testSectionedEmptyChangesets", testSectionedEmptyChangesets),
        ("testSectionInserted", testSectionInserted),
        ("testSectionMoved", testSectionMoved),
        ("testSectionUpdated", testSectionUpdated),
        ("testUpdated", testUpdated),
    ]
}

extension AnyDifferentiableTestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnyDifferentiableTestCase = [
        ("testHashable", testHashable),
        ("testRedundantWrapping", testRedundantWrapping),
    ]
}

extension ArraySectionTestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArraySectionTestCase = [
        ("testReinitialize", testReinitialize),
    ]
}

extension ChangesetTestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ChangesetTestCase = [
        ("testchangeCount", testchangeCount),
        ("testEquatable", testEquatable),
        ("testHasChanges", testHasChanges),
    ]
}

extension ContentEquatableTestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ContentEquatableTestCase = [
        ("testEquatableValue", testEquatableValue),
        ("testOptionalValue", testOptionalValue),
    ]
}

extension ElementPathTestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ElementPathTestCase = [
        ("testHashable", testHashable),
    ]
}

extension MeasurementTestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MeasurementTestCase = [
        ("testMeasureAlgorithmForLinearCollection", testMeasureAlgorithmForLinearCollection),
        ("testMeasureAlgorithmForSectionedCollection", testMeasureAlgorithmForSectionedCollection),
    ]
}

extension StagedChangesetTestCase {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StagedChangesetTestCase = [
        ("testEquatable", testEquatable),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AlgorithmTestCase.__allTests__AlgorithmTestCase),
        testCase(AnyDifferentiableTestCase.__allTests__AnyDifferentiableTestCase),
        testCase(ArraySectionTestCase.__allTests__ArraySectionTestCase),
        testCase(ChangesetTestCase.__allTests__ChangesetTestCase),
        testCase(ContentEquatableTestCase.__allTests__ContentEquatableTestCase),
        testCase(ElementPathTestCase.__allTests__ElementPathTestCase),
        testCase(MeasurementTestCase.__allTests__MeasurementTestCase),
        testCase(StagedChangesetTestCase.__allTests__StagedChangesetTestCase),
    ]
}
#endif
